version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: lab_rabbitmq
    ports:
      - 15672:15672 #web
      - 5672:5672 #amqp
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    container_name: lab_mssql
    ports:
      - 1433:1433 #sql
    volumes:
      - D:\repositories\kubernetes\mssql_maalsi_data:/var/opt/mssql/data/
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd2023!
  api:
    build: ./RabbitMqProductAPI
    # scale: 3
    expose:
      - 80
    environment:
      - ConnectionStrings__DefaultConnection=Server=tcp:mssql,1433;Initial Catalog=RabbitMqDemo;Persist Security Info=False;User ID=sa;Password=P@ssw0rd2023!;Connection Timeout=30;
      - RabbitMQ__Hostname=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin
    depends_on:
      - rabbitmq
      - mssql
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:8081"
    depends_on:
      - api
  console:
    build: ./RabbitMQProduct.ConsoleApplication
    container_name: lab_console
    environment:
      - RabbitMQ__Hostname=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin
    # depends_on:
    #   rabbitmq:
    #     condition: service_healthy