apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
spec:
  serviceName: mssql
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mssql
  template:
    metadata:
      labels:
        io.kompose.service: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: P@ssw0rd2023!
            - name: MSSQL_PID
              value: "Developer"
          volumeMounts:
            - mountPath: /var/opt/mssql/data/
              name: mssql-claim0
      volumes:
        - name: mssql-claim0
          hostPath:
            path: /run/desktop/mnt/host/d/repositories/kubernetes/mssql_data_2
            type: DirectoryOrCreate
