apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mssql
  name: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mssql
  template:
    metadata:
      labels:
        io.kompose.service: mssql
    spec:
      volumes:
        - name: mssql-claim0
          hostPath:
            path: /run/desktop/mnt/host/d/repositories/kubernetes/mssql_data
            type: DirectoryOrCreate