apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  nginx.conf: |
    user  nginx;events {
        worker_connections   1000;
    }
    http {
      server {
        listen 8081;
        location / {
          proxy_pass http://api:80;
        }
      }
    }