apiVersion: v1
kind: Secret
metadata:
  name: api
type: Opaque
data:
  mssql_root_username: c2EK
  mssql_root_password: UEBzc3cwcmQyMDIzIQo=
  rabbitmq_password: YWRtaW4=
  rabbitmq_username: YWRtaW4=